### ISSUE TITLE
wrong simulator names: fail

### ISSUE THREAD

**Issue by markusfassbender** [jonathanpenn/ui-screen-shooter#88]
Hi the example app fails because the simlator names seems to be wrong. can you give me a hint how to change the names?

`Instruments failed to start up... retrying in 2 seconds
Instruments Usage Error : Unknown device specified: "iPhone 6 (8.3 Simulator),"
Known Devices:
Mac mini [8F362539-D859-561F-9ABB-626D1F907A33]
Apple TV 1080p (9.0) [125AA8D7-B094-4EF7-ABA2-972EAACDDAA9]
[...watch, ipads etc...]
iPhone 6 (8.3) [6D054895-9A0B-45AA-A341-CA4EBEE1B15B]
iPhone 6 (8.4) [1AC6DA1C-FE08-4C3B-8706-431754F682E5]
iPhone 6 (9.1) [34DC8162-28A2-4DC6-9C05-C0CE0566C8D9]
iPhone 6 Plus (8.3) [150AADEF-9D1E-4083-AE7D-2F5B24C81B67]
iPhone 6 Plus (8.4) [3E1B51A5-19E3-4A7A-93E3-B387A52E9B57]
iPhone 6 Plus (9.1) [747A5C78-C097-4C56-B25D-99FAC9FD998E]
iPhone 6s (9.1) [B2465043-63E9-4DC1-8A69-52BC60805E03]
iPhone 6s (9.1) + Apple Watch - 38mm (2.0) [217901AA-F48B-4D94-B8A9-5A70B3A58A2F]
iPhone 6s Plus (9.1) [EA8D05CA-401F-4865-A1D0-022A99099346]
iPhone 6s Plus (9.1) + Apple Watch - 42mm (2.0) [B159CF69-0A57-46AE-B015-34D36E172942]
Instruments failed to start up... retrying in 2 seconds

**Comment by dermaaarkus** [comment]
i'm now using fastlane, but thanks for your work anyway :)
